# 配置服务开启端口
#server:
#    port: 8080#    servlet:#        context-path: /api
        
server:
  port: 8443
  servlet:
        context-path: /api
  http:
    port: 8989
  ssl:
    client-auth: 
    key-store: classpath:kamfu.p12
    key-store-password: 123456
    key-alias: kamfu
    key-store-type: PKCS12

spring:
    jackson:
      date-format: YYYY-MM-dd HH:mm:ss
      time-zone: GMT+8
    # 配置服务的名称.
    application:
        name: adminserver
    # redis 配置
    redis:
    # 地址
       host: ${REDIS_HOST:localhost}
    # 端口，默认为6379
       port: ${REDIS_PORT:6379}
       
#    # 连接超时时间
#       timeout: 10s
#       lettuce:
#          pool:
#             # 连接池中的最小空闲连接
#             min-idle: 0
#             # 连接池中的最大空闲连接
#             max-idle: 8
#             # 连接池的最大数据库连接数
#             max-active: 8
#             # #连接池最大阻塞等待时间（使用负值表示没有限制）
#             max-wait: -1ms
###   数据库配置
##    单数据源配置解开一个数据源,当需要配置多个时候,按照下面例子再写一个就可以,
##    就是写多个  datasource,但是 name 不能重复
#    datasource:
#        name: master
#        # mysql 连接
#        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/tas?useUnicode=true&characterEncoding=UTF8&useSSL=true
#        username: root
#        password: 123456
   
    datasource:
        name: test
#        url: jdbc:mysql://${MYSQL_HOST:192.168.5.33}:${MYSQL_PORT:3306}/kamfu-admin?useUnicode=true&characterEncoding=UTF8
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/tas?useUnicode=true&characterEncoding=UTF8&useSSL=false
#        url: jdbc:mysql://${MYSQL_HOST:139.159.140.230}:${MYSQL_PORT:3306}/kamfu-admin?useUnicode=true&characterEncoding=UTF8
        username: root
#        password: password：
        password: ${DB_PASSWORD:wangshun}
#        password: wangshun
        driver-class-name: com.mysql.jdbc.Driver



## 如果使用 mybatis maven 生成插件, 请打开注释
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"


jwt:
  token-header: Authorization
  # token超时时间(秒) 
  expire: 36000
  rsa-secret: xx1WET12^%3^(WE45

client:
  secret: 123456
  token-header: client-token
  expire: 3600
  rsa-secret: x2318^^(*WRYQWR(QW&T

aec:
  aec-key: xx288&^^%$!@#4dc
  aec-iv: 0123456789abcdef









